// <auto-generated />
using ExamenT1P2AxelDelSolar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenT1P2AxelDelSolar.Migrations
{
    [DbContext(typeof(DataDBContext))]
    [Migration("20251126062808_CorregirTablaNivelAcademico")]
    partial class CorregirTablaNivelAcademico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExamenT1P2AxelDelSolar.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("curso_id");

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_curso");

                    b.Property<int>("Creditos")
                        .HasColumnType("int")
                        .HasColumnName("creditos");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int")
                        .HasColumnName("horas_semanales");

                    b.Property<int>("NivelAcademicoId")
                        .HasColumnType("int")
                        .HasColumnName("nivel_academico_id");

                    b.HasKey("CursoId");

                    b.HasIndex("NivelAcademicoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            CodigoCurso = "CS101",
                            Creditos = 4,
                            HorasSemanales = 6,
                            NivelAcademicoId = 1
                        },
                        new
                        {
                            CursoId = 2,
                            CodigoCurso = "CS102",
                            Creditos = 5,
                            HorasSemanales = 6,
                            NivelAcademicoId = 1
                        },
                        new
                        {
                            CursoId = 3,
                            CodigoCurso = "MST500",
                            Creditos = 5,
                            HorasSemanales = 5,
                            NivelAcademicoId = 2
                        },
                        new
                        {
                            CursoId = 4,
                            CodigoCurso = "DIP001",
                            Creditos = 3,
                            HorasSemanales = 3,
                            NivelAcademicoId = 3
                        });
                });

            modelBuilder.Entity("ExamenT1P2AxelDelSolar.Models.NivelAcademico", b =>
                {
                    b.Property<int>("NivelAcademicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nivel_academico_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("NivelAcademicoId");

                    b.ToTable("nivel_academico");

                    b.HasData(
                        new
                        {
                            NivelAcademicoId = 1,
                            Descripcion = "Pregrado",
                            Orden = 1
                        },
                        new
                        {
                            NivelAcademicoId = 2,
                            Descripcion = "Maestría",
                            Orden = 2
                        },
                        new
                        {
                            NivelAcademicoId = 3,
                            Descripcion = "Diplomado",
                            Orden = 3
                        });
                });

            modelBuilder.Entity("ExamenT1P2AxelDelSolar.Models.Curso", b =>
                {
                    b.HasOne("ExamenT1P2AxelDelSolar.Models.NivelAcademico", "NivelAcademico")
                        .WithMany("Cursos")
                        .HasForeignKey("NivelAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAcademico");
                });

            modelBuilder.Entity("ExamenT1P2AxelDelSolar.Models.NivelAcademico", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
